/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_ManipulaCursos;
import Controlador.Controlador_ManipulaEstudiantes;

/**
 *
 * @author Carolina
 */
public class GUI_Botones extends javax.swing.JPanel {

    /**
     * Creates new form GUI_Botones
     */
    public GUI_Botones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        btnEditar.setText("Editar");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void agregar_eventos(Controlador_ManipulaEstudiantes controlador_ManipulaEstudiantes){
    
        this.btnAgregar.addActionListener(controlador_ManipulaEstudiantes);
        this.btnBuscar.addActionListener(controlador_ManipulaEstudiantes);
        this.btnEditar.addActionListener(controlador_ManipulaEstudiantes);
        this.btnEliminar.addActionListener(controlador_ManipulaEstudiantes);
    }
    
    public void agregar_eventos_cursos(Controlador_ManipulaCursos controlador_ManipulaCursos){
    
        this.btnAgregar.addActionListener(controlador_ManipulaCursos);
        this.btnBuscar.addActionListener(controlador_ManipulaCursos);
        this.btnEditar.addActionListener(controlador_ManipulaCursos);
        this.btnEliminar.addActionListener(controlador_ManipulaCursos);
    }
    
    public int get_codigo_por_fuente (Object obj){
     int dev =0;
        if(this.btnAgregar.equals(obj)){
                dev = Controlador_ManipulaEstudiantes.AGREGAR;
            }else if(this.btnBuscar.equals(obj)){
                dev = Controlador_ManipulaEstudiantes.BUSCAR;
            }else if(this.btnEditar.equals(obj)){
                dev = Controlador_ManipulaEstudiantes.EDITAR;
            }else if(this.btnEliminar.equals(obj)){
                dev = Controlador_ManipulaEstudiantes.ELIMINAR;
            }
     return dev;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    // End of variables declaration//GEN-END:variables
}
