/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_ManipulaCursos;
import Modelo.Curso;

/**
 *
 * @author Carolina
 */
public class ManipulaCursos extends javax.swing.JFrame {

    private Controlador_ManipulaCursos cmc;
    /**
     * Creates new form ManipulaCursos
     */
    public ManipulaCursos() {
        initComponents();
        cmc = new Controlador_ManipulaCursos(this);
        this.gUI_Botones1.agregar_eventos_cursos(cmc);
    }
    
    public Curso getCurso(){
        Curso c = new Curso(txt_Siglas.getText(), txt_Nombre.getText(),Integer.parseInt(txt_Creditos.getText()));
        return c;  
    }
    public boolean verificarEspacios(){
        if(txt_Siglas.getText().equals("")|| txt_Nombre.getText().equals("")|| txt_Creditos.getText().equals("")){
            return true;
        }
        return false;
    }
    public boolean verificarSiglas(){
        if(txt_Siglas.getText().equals("")){
            return true;
        }
        return false;
    }
    public String getTxtSiglas() {
        return txt_Siglas.getText();
    } 
    public String getTxtNombre() {
        return txt_Nombre.getText();
    } 
    public String getTxtCreditos() {
        return txt_Creditos.getText();
    } 
    public void setTxtNombre(String nombre) {
        this.txt_Nombre.setText(nombre);
    }
    public void setTxtSiglas(String siglas) {
        this.txt_Siglas.setText(siglas);
    }
    public void setTxtCreditos(String creditos) {
        this.txt_Creditos.setText(creditos);
    }
    public void limpiar(){
       txt_Creditos.setText("");
       txt_Nombre.setText("");
       txt_Siglas.setText("");
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Siglas = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Creditos = new javax.swing.JTextField();
        gUI_Botones1 = new Vista.GUI_Botones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Siglas:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Creditos:");

        txt_Siglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SiglasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Siglas)
                    .addComponent(txt_Nombre)
                    .addComponent(txt_Creditos, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Siglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Creditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_SiglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SiglasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SiglasActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public int getCodigo(Object obj){
       int dev = 0;
            if(this.txt_Siglas.equals(obj)){
                dev = Controlador_ManipulaCursos.SIGLAS;
            }else if(this.txt_Nombre.equals(obj)){
                dev = Controlador_ManipulaCursos.NOMBRE;
            }else if(this.txt_Creditos.equals(obj)){
                dev = Controlador_ManipulaCursos.CREDITOS;
            }else{
                dev = this.gUI_Botones1.get_codigo_por_fuente(obj);
            }
        
       return dev;
   }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Creditos;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Siglas;
    // End of variables declaration//GEN-END:variables
}
